# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=50)),
            ],
        ),
    ]
